### ISSUE TITLE
white blank page

### ISSUE THREAD

**Issue by nolbyte** [cu-library/OJS-Modern-Theme#13]
Hi
I've tried to install this awesome theme on my OJS 2.4.5, but I only got white blank page after activate this theme. Is there any others way to make this theme work?
Thank you very much

**Comment by cudevmaxwell** [comment]
Thank you for your interest, @nolbyte. Unfortunately, this theme is no longer maintained, due to some problems I had with hardcoded HTML in the OJS 2 release. When OJS 3 is released, I plan to continue work on this theme, using OJS 3 and the newest Bootstrap release. 

So sorry for the inconvenience!
